package com.gempire.util;

import com.gempire.init.ModBlocks;
import net.minecraft.world.level.block.Blocks;

import java.util.ArrayList;

public class InjectionRegistry {
    public static ArrayList<GemInfo> list = new ArrayList<>();
    public static ArrayList<CruxInfo> blockList = new ArrayList<>();
    public static void setMap() {
        list.add(new GemInfo(new int[]{10, 5, 5, 5, 5}, 0, "agate"));
        list.add(new GemInfo(new int[]{5, 10, 10, 5, 5}, 0, "aquamarine"));
        list.add(new GemInfo(new int[]{5, 5, 4, 5, 5}, 0, "bismuth"));
        list.add(new GemInfo(new int[]{2, 5, 4, 5, 5}, 0, "bixbite"));
        list.add(new GemInfo(new int[]{1, 5, 4, 5, 5}, 0, "emerald"));
        list.add(new GemInfo(new int[]{4, 5, 4, 5, 5}, 0, "garnet"));
        list.add(new GemInfo(new int[]{8, 5, 4, 5, 5}, 0, "jasper"));
        list.add(new GemInfo(new int[]{4, 5, 4, 5, 5}, 0, "lapis_lazuli"));
        list.add(new GemInfo(new int[]{3, 5, 4, 5, 5}, 0, "larimar"));
        list.add(new GemInfo(new int[]{7, 5, 4, 5, 5}, 0, "morganite"));
        list.add(new GemInfo(new int[]{9, 5, 4, 5, 5}, 0, "nephrite"));
        list.add(new GemInfo(new int[]{8, 5, 4, 5, 5}, 0, "obsidian"));
        list.add(new GemInfo(new int[]{3, 5, 4, 5, 5}, 0, "peridot"));
        list.add(new GemInfo(new int[]{4, 5, 4, 5, 5}, 0, "quartz"));
        list.add(new GemInfo(new int[]{1, 5, 4, 5, 5}, 0, "ruby"));
        list.add(new GemInfo(new int[]{5, 5, 4, 5, 5}, 0, "rutile"));
        list.add(new GemInfo(new int[]{7, 5, 4, 5, 5}, 0, "sapphire"));
        list.add(new GemInfo(new int[]{6, 5, 4, 5, 5}, 0, "spinel"));
        list.add(new GemInfo(new int[]{4, 5, 4, 5, 5}, 0, "spodumene"));
        list.add(new GemInfo(new int[]{3, 5, 4, 5, 5}, 0, "topaz"));
        list.add(new GemInfo(new int[]{7, 5, 4, 5, 5}, 0, "tourmaline"));
        list.add(new GemInfo(new int[]{9, 5, 4, 5, 5}, 0, "zircon"));
        //0 - organic
        //1 - mystical
        //2 - crystalline
        //3 - metallic
        //4 - igneous
        //5 - moisture
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.ROOTED_DIRT, "rooted_dirt"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 0, 1}, Blocks.MUD, "mud"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 0, 2}, Blocks.CLAY, "clay"));
        blockList.add(new CruxInfo(new int[]{2, 0, 0, 0, 0, 0}, Blocks.MOSS_BLOCK, "moss_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.GRANITE, "granite"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.DIORITE, "diorite"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.CALCITE, "calcite"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.DRIPSTONE_BLOCK, "dripstone_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.BLACKSTONE, "blackstone"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 1, 0}, Blocks.ANDESITE, "andesite"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 2, 0}, Blocks.TUFF, "tuff"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 0, 3}, Blocks.PRISMARINE, "prismarine"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 3, 0}, Blocks.MAGMA_BLOCK, "magma_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 3, 0}, Blocks.OBSIDIAN, "obsidian"));
        blockList.add(new CruxInfo(new int[]{0, 1, 1, 0, 5, 0}, Blocks.CRYING_OBSIDIAN, "crying_obsidian"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SOUL_SAND, "soul_sand"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.BONE_BLOCK, "bone_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 4, 0}, Blocks.BASALT, "basalt"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.COAL_ORE, "coal_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.DEEPSLATE_COAL_ORE, "deepslate_coal_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.COAL_BLOCK, "coal_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, Blocks.IRON_ORE, "iron_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, Blocks.DEEPSLATE_IRON_ORE, "deepslate_iron_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 3, 0, 0}, Blocks.RAW_IRON_BLOCK, "raw_iron_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 4, 0, 0}, Blocks.IRON_BLOCK, "iron_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 3, 0, 0}, Blocks.GOLD_ORE, "gold_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 3, 0, 0}, Blocks.DEEPSLATE_GOLD_ORE, "deepslate_gold_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 4, 0, 0}, Blocks.RAW_GOLD_BLOCK, "raw_gold_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 5, 0, 0}, Blocks.GOLD_BLOCK, "gold_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 1, 0, 0}, Blocks.COPPER_ORE, "copper_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 1, 0, 0}, Blocks.DEEPSLATE_COPPER_ORE, "deepslate_copper_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, Blocks.RAW_COPPER_BLOCK, "raw_copper_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 3, 0, 0}, Blocks.COPPER_BLOCK, "copper_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, ModBlocks.TUNGSTEN_ORE.get(), "tungsten_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, ModBlocks.DEEPSLATE_TUNGSTEN_ORE.get(), "deepslate_tungsten_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 3, 0, 0}, ModBlocks.RAW_TUNGSTEN_BLOCK.get(), "raw_tungsten_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 4, 0, 0}, ModBlocks.TUNGSTEN_BLOCK.get(), "tungsten_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 4, 0, 0}, ModBlocks.PRISMATIC_BLOCK.get(), "prismatic_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.REDSTONE_ORE, "redstone_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 1, 0, 0, 0}, Blocks.DEEPSLATE_REDSTONE_ORE, "deepslate_redstone_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.REDSTONE_BLOCK, "redstone_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 3, 0, 0, 0}, Blocks.EMERALD_ORE, "emerald_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 3, 0, 0, 0}, Blocks.DEEPSLATE_EMERALD_ORE, "deepslate_emerald_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 4, 0, 0, 0}, Blocks.EMERALD_BLOCK, "emerald_block"));
        blockList.add(new CruxInfo(new int[]{0, 2, 2, 0, 0, 0}, Blocks.LAPIS_ORE, "lapis_ore"));
        blockList.add(new CruxInfo(new int[]{0, 2, 2, 0, 0, 0}, Blocks.DEEPSLATE_LAPIS_ORE, "deepslate_lapis_ore"));
        blockList.add(new CruxInfo(new int[]{0, 2, 3, 0, 0, 0}, Blocks.LAPIS_BLOCK, "lapis_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 5, 0, 0, 0}, Blocks.DIAMOND_ORE, "diamond_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 5, 0, 0, 0}, Blocks.DEEPSLATE_DIAMOND_ORE, "deepslate_diamond_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 6, 0, 0, 0}, Blocks.DIAMOND_BLOCK, "diamond_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.NETHER_QUARTZ_ORE, "nether_quartz_ore"));
        blockList.add(new CruxInfo(new int[]{0, 0, 3, 0, 0, 0}, Blocks.QUARTZ_BLOCK, "quartz_block"));
        blockList.add(new CruxInfo(new int[]{0, 2, 4, 0, 0, 0}, Blocks.ANCIENT_DEBRIS, "ancient_debris"));
        blockList.add(new CruxInfo(new int[]{0, 2, 6, 0, 0, 0}, Blocks.NETHERITE_BLOCK, "netherite_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 3, 0, 0, 0}, Blocks.GLOWSTONE, "glowstone"));
        blockList.add(new CruxInfo(new int[]{0, 0, 3, 0, 0, 0}, Blocks.AMETHYST_BLOCK, "amethyst_block"));
        blockList.add(new CruxInfo(new int[]{0, 0, 5, 0, 0, 0}, Blocks.BUDDING_AMETHYST, "budding_amethyst"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.AMETHYST_CLUSTER, "amethyst_cluster"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.SMALL_AMETHYST_BUD, "small_amethyst_bud"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.MEDIUM_AMETHYST_BUD, "medium_amethyst_bud"));
        blockList.add(new CruxInfo(new int[]{0, 0, 2, 0, 0, 0}, Blocks.LARGE_AMETHYST_BUD, "large_amethyst_bud"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.OAK_LOG, "oak_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.DARK_OAK_LOG, "dark_oak_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.BIRCH_LOG, "birch_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.SPRUCE_LOG, "spruce_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.JUNGLE_LOG, "jungle_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.ACACIA_LOG, "acacia_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.MANGROVE_LOG, "mangrove_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.CHERRY_LOG, "cherry_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_OAK_LOG, "stripped_oak_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_DARK_OAK_LOG, "stripped_dark_oak_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_BIRCH_LOG, "stripped_birch_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_SPRUCE_LOG, "stripped_spruce_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_JUNGLE_LOG, "stripped_jungle_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_ACACIA_LOG, "stripped_acacia_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_MANGROVE_LOG, "stripped_mangrove_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_CHERRY_LOG, "stripped_cherry_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.OAK_WOOD, "oak_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.DARK_OAK_WOOD, "dark_oak_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.BIRCH_WOOD, "birch_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.SPRUCE_WOOD, "spruce_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.JUNGLE_WOOD, "jungle_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.ACACIA_WOOD, "acacia_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.MANGROVE_WOOD, "mangrove_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.CHERRY_WOOD, "cherry_log"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_OAK_WOOD, "stripped_oak_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_DARK_OAK_WOOD, "stripped_dark_oak_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_BIRCH_WOOD, "stripped_birch_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_SPRUCE_WOOD, "stripped_spruce_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_JUNGLE_WOOD, "stripped_jungle_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_ACACIA_WOOD, "stripped_acacia_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_MANGROVE_WOOD, "stripped_mangrove_wood"));
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 0}, Blocks.STRIPPED_CHERRY_WOOD, "stripped_cherry_wood"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.OAK_LEAVES, "oak_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.DARK_OAK_LEAVES, "dark_oak_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.BIRCH_LEAVES, "birch_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.SPRUCE_LEAVES, "spruce_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.JUNGLE_LEAVES, "jungle_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.ACACIA_LEAVES, "acacia_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.MANGROVE_LEAVES, "mangrove_leaves"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.CHERRY_LEAVES, "cherry_log"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.CRIMSON_STEM, "crimson_stem"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.STRIPPED_CRIMSON_STEM, "stripped_crimson_stem"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.CRIMSON_HYPHAE, "crimson_hyphae"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.STRIPPED_CRIMSON_HYPHAE, "stripped_crimson_hyphae"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.NETHER_WART_BLOCK, "nether_wart_block"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.WARPED_STEM, "warped_stem"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.STRIPPED_WARPED_STEM, "stripped_warped_stem"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.WARPED_HYPHAE, "warped_hyphae"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.STRIPPED_WARPED_HYPHAE, "stripped_warped_hyphae"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.WARPED_WART_BLOCK, "warped_hyphae"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.MUSHROOM_STEM, "mushroom_stem"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.BROWN_MUSHROOM_BLOCK, "brown_mushroom_block"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 0}, Blocks.RED_MUSHROOM_BLOCK, "red_mushroom_block"));
        blockList.add(new CruxInfo(new int[]{2, 0, 0, 0, 0, 3}, Blocks.SEA_PICKLE, "sea_pickle"));
        blockList.add(new CruxInfo(new int[]{2, 0, 0, 0, 0, 3}, Blocks.KELP, "kelp"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 4}, Blocks.DRIED_KELP_BLOCK, "dried_kelp_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.SPONGE, "sponge"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.WET_SPONGE, "wet_sponge"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.BRAIN_CORAL_BLOCK, "brain_coral_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.BUBBLE_CORAL_BLOCK, "bubble_coral_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.FIRE_CORAL_BLOCK, "fire_coral_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.HORN_CORAL_BLOCK, "horn_coral_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 5}, Blocks.TUBE_CORAL_BLOCK, "tube_coral_block"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.BRAIN_CORAL_FAN, "brain_coral_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.BUBBLE_CORAL_FAN, "bubble_coral_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.FIRE_CORAL_FAN, "fire_coral_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.HORN_CORAL_FAN, "horn_coral_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.TUBE_CORAL_FAN, "tube_coral_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.BRAIN_CORAL_WALL_FAN, "brain_coral_wall_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.BUBBLE_CORAL_WALL_FAN, "bubble_coral_wall_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.FIRE_CORAL_WALL_FAN, "fire_coral_wall_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.HORN_CORAL_WALL_FAN, "horn_coral_wall_fan"));
        blockList.add(new CruxInfo(new int[]{1, 0, 0, 0, 0, 2}, Blocks.TUBE_CORAL_WALL_FAN, "tube_coral_wall_fan"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.MELON, "melon"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.PUMPKIN, "pumpkin"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.CARVED_PUMPKIN, "carved_pumpkin"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.HAY_BLOCK, "hay_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.BEEHIVE, "beehive"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.HONEYCOMB_BLOCK, "honeycomb_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.HONEY_BLOCK, "honey_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.SLIME_BLOCK, "slime_block"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.OCHRE_FROGLIGHT, "ochre_froglight"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.VERDANT_FROGLIGHT, "verdant_froglight"));
        blockList.add(new CruxInfo(new int[]{3, 0, 0, 0, 0, 0}, Blocks.PEARLESCENT_FROGLIGHT, "pearlescent_froglight"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SCULK, "sculk"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SCULK_CATALYST, "sculk_catalyst"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SCULK_SENSOR, "sculk_sensor"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SCULK_SHRIEKER, "sculk_shrieker"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.SCULK_VEIN, "sculk_vein"));
        //TODO: decorative plants flowers bushes fungi etc +4 organic
        blockList.add(new CruxInfo(new int[]{4, 0, 0, 0, 0, 1}, Blocks.MUDDY_MANGROVE_ROOTS, "muddy_mangrove_roots"));
        blockList.add(new CruxInfo(new int[]{0, 4, 0, 0, 0, 6}, Blocks.CONDUIT, "conduit"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.RED_CHROMA_CRYSTAL.get(), "red_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.ORANGE_CHROMA_CRYSTAL.get(), "orange_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.YELLOW_CHROMA_CRYSTAL.get(), "yellow_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.LIME_CHROMA_CRYSTAL.get(), "lime_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.GREEN_CHROMA_CRYSTAL.get(), "green_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.CYAN_CHROMA_CRYSTAL.get(), "cyan_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.LIGHT_BLUE_CHROMA_CRYSTAL.get(), "light_blue_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.BLUE_CHROMA_CRYSTAL.get(), "blue_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.PURPLE_CHROMA_CRYSTAL.get(), "purple_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.MAGENTA_CHROMA_CRYSTAL.get(), "magenta_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.PINK_CHROMA_CRYSTAL.get(), "pink_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.WHITE_CHROMA_CRYSTAL.get(), "white_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.LIGHT_GRAY_CHROMA_CRYSTAL.get(), "light_gray_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.GRAY_CHROMA_CRYSTAL.get(), "gray_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.BLACK_CHROMA_CRYSTAL.get(), "black_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 3, 4, 0, 0, 0}, ModBlocks.BROWN_CHROMA_CRYSTAL.get(), "brown_chroma_crystal"));
        blockList.add(new CruxInfo(new int[]{0, 5, 0, 0, 0, 0}, Blocks.BEACON, "beacon"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.LODESTONE, "lodestone"));
        blockList.add(new CruxInfo(new int[]{0, 4, 1, 0, 2, 0}, Blocks.RESPAWN_ANCHOR, "respawn_anchor"));
        blockList.add(new CruxInfo(new int[]{0, 6, 0, 0, 0, 0}, Blocks.REINFORCED_DEEPSLATE, "reinforced_deepslate"));
        blockList.add(new CruxInfo(new int[]{0, 1, 0, 0, 0, 0}, Blocks.BOOKSHELF, "bookshelf"));
        blockList.add(new CruxInfo(new int[]{0, 1, 0, 0, 0, 0}, Blocks.CHISELED_BOOKSHELF, "chiseled_bookshelf"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 0}, Blocks.BREWING_STAND, "brewing_stand"));
        blockList.add(new CruxInfo(new int[]{0, 4, 0, 0, 0, 0}, Blocks.ENCHANTING_TABLE, "enchanting_table"));
        blockList.add(new CruxInfo(new int[]{0, 3, 0, 0, 0, 0}, Blocks.ENDER_CHEST, "ender_chest"));
        blockList.add(new CruxInfo(new int[]{1, 0, 1, 0, 0, 0}, Blocks.MOSSY_COBBLESTONE, "mossy_cobblestone"));
        blockList.add(new CruxInfo(new int[]{1, 0, 1, 0, 0, 0}, Blocks.MOSSY_STONE_BRICKS, "mossy_stone_bricks"));
        blockList.add(new CruxInfo(new int[]{1, 0, 1, 0, 0, 0}, Blocks.INFESTED_MOSSY_STONE_BRICKS, "infested_mossy_stone_bricks"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 0, 0, 2}, Blocks.PACKED_MUD, "packed_mud"));
        blockList.add(new CruxInfo(new int[]{0, 2, 0, 0, 0, 4}, Blocks.SEA_LANTERN, "sea_lantern"));
        blockList.add(new CruxInfo(new int[]{0, 3, 0, 2, 0, 0}, Blocks.GILDED_BLACKSTONE, "gilded_blackstone"));
        blockList.add(new CruxInfo(new int[]{0, 0, 0, 2, 0, 0}, Blocks.NETHER_GOLD_ORE, "nether_gold_ore"));
        blockList.add(new CruxInfo(new int[]{0, 1, 3, 0, 0, 0}, Blocks.PURPUR_BLOCK, "purpur_block"));
        blockList.add(new CruxInfo(new int[]{0, 1, 3, 0, 0, 0}, Blocks.PURPUR_PILLAR, "purpur_pillar"));
    }
}
